animal_details/urls.py
from django.conf.urls import url
from . import views

app_name='animal_details'
urlpatterns = [

    url(r'^home/$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'animal/add/$',views.AnimalCreate.as_view(),name='animal-add'),

    url(r'animal/(?P<pk>[0-9]+)/$', views.AnimalUpdate.as_view(), name='animal-update'),

    url(r'animal/(?P<pk>[0-9]+)/delete/$', views.AnimalDelete.as_view(), name='animal-delete'),

    url(r'medicines/$',views.MedicineDetail.as_view(),name='med-detail'),
    url(r'medicines/add/$',views.MedicineCreate.as_view(),name='medicine-add'),
    url(r'medicines/(?P<pk>[0-9]+)/$',views.MedicineUpdate.as_view(),name='medicine-update'),

    url(r'account/$',views.AccountDetail.as_view(),name='acc-detail'),
    url(r'account/add/$',views.AccountCreate.as_view(),name='account-add'),
    url(r'account/(?P<pk>[0-9]+)/$',views.AccountUpdate.as_view(),name='account-update'),

    url(r'Organisation_grants/$',views.GrantsDetail.as_view(),name='grant-detail'),
    url(r'Organisation_grants/add/$',views.GrantsUpdate.as_view(),name='Org-grant-add'),
    url(r'Organisation_grants/(?P<pk>[0-9]+)/$',views.GrantsUpdate.as_view(),name='grant-Update'),

    #/Staff/
    url(r'Staff/$',views.StaffDetail.as_view(),name='Staff-detail'),
    #/Staff/add/
    url(r'Staff/add/$', views.StaffCreate.as_view(),name='Staff-add'),
    #/Staff/pk/
    url(r'Staff/(?P<pk>[0-9]+)/$', views.StaffUpdate.as_view(), name='Staff-update'),
     url(r'Staff/(?P<pk>[0-9]+)/delete/$', views.StaffDelete.as_view(), name='Staff-delete'),

    #/Tourist/
    url(r'Tourist/$',views.TouristDetail.as_view(),name='Tourist-detail'),
    #/Tourist/add/
    url(r'Tourist/add/$', views.TouristCreate.as_view(),name='Tourist-add'),
    #/Tourist/pk/
    url(r'Tourist/(?P<pk>[0-9]+)/$', views.TouristUpdate.as_view(), name='Tourist-update'),

     ]

wildlife_sanctuary/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Sanctuary/',include('animal_details.urls')),
]

if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

animal_details/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Animal(models.Model):
    id=models.AutoField(primary_key=True)
    Animal_species=models.CharField(max_length=100)
    Animal_count=models.IntegerField(default=0)
    Animal_type=models.CharField(max_length=20)
    Scientific_name=models.CharField(max_length=100)
    Country=models.CharField(max_length=100)
    Animal_feed=models.CharField(max_length=100)
    Feed_cost=models.FloatField(default=0)
    Animal_image=models.FileField(null=True,blank=True)
 
    def get_absolute_url(self):
        return reverse('animal_details:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return str(self.id)+' - '+(self.Animal_species)

class Medicine(models.Model):
    Animal_id=models.ForeignKey(Animal,on_delete=models.CASCADE)
    Medicine_name=models.CharField(max_length=200)
    Medicine_cost=models.FloatField(default=0.0)
    Date=models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('animal_details:med-detail')

    def __str__(self):

        return str(self.Animal_id)+' on '+str(self.Date)

class Accounts(models.Model):
    id=models.AutoField(primary_key=True)
    Date=models.DateField(auto_now=True)
    Income=models.FloatField(default=0.0)
    Expenditure=models.FloatField(default=0.0)

    def get_absolute_url(self):
        return reverse('animal_details:acc-detail')

    def __str__(self):
        return str(self.id)+' on '+str(self.Date)

class Organisation_grants(models.Model):
    id=models.AutoField(primary_key=True)
    Organisation_name=models.CharField(max_length=200)
    Organisation_phno=models.CharField(max_length=20)
    Address=models.CharField(max_length=300)
    Amount=models.FloatField(default=0.0)
    Date=models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('animal_details:org-detail',kwargs={'pk':self.pk})

    def __str__(self):
         return str(self.Organisation_name)+' - '+(self.Amount)



class Staff(models.Model):
    id=models.AutoField(primary_key=True)
    Staff_Name=models.CharField(max_length=100)
    Designation=models.CharField(max_length=50)
    Salary=models.FloatField(default=0.0)

    def get_absolute_url(self):
        return reverse('animal_details:Staff-detail')

    def __str__(self):
         return str(self.id)+' - '+(self.Salary)


class Tourists(models.Model):
    id= models.AutoField(primary_key=True)
    Tourists_name=models.CharField(max_length=100)
    Donation=models.FloatField(default=0.0)
    Date=models.DateField(auto_now=True)
    GuideName=models.CharField(max_length=100)
    Phone_number=models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('animal_details:Tourist-detail')

    def __str__(self):
         return str(self.id)+' - '+(self.Tourists_name)

animal_details/forms.py
from django import forms
from django.contrib.auth.models import User







class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

animal_details/views.py
from django.contrib.auth import authenticate, login,logout
from django.views import generic
from .models import Animal,Medicine,Accounts,Organisation_grants,Staff,Tourists
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View

from .forms import UserForm




def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                animal=Animal.objects.all()
               
                return render(request, 'animal_details/index1.html', {'animals': animal})
    context = {
        "form": form,
    }
    return render(request, 'animal_details/register.html', context)


def home(request):
    return render(request,'animal_details/home.html')




def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                animal=Animal.objects.all()
               
                return render(request, 'animal_details/index1.html', {'animals': animal})
               
            else:
                return render(request, 'animal_details/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'animal_details/login.html', {'error_message': 'Invalid login'})
    return render(request, 'animal_details/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'animal_details/login.html', context)






class IndexView(generic.ListView):
    template_name = 'animal_details/index.html'

    def get_queryset(self):
        return Animal.objects.all()

class DetailView(generic.DetailView):
    model = Animal
    template_name = 'animal_details/detail.html'
#-----------------------------------------------------------------------------------------------------------------------

class AnimalCreate(CreateView):
    model = Animal
    fields = ['id', 'Animal_species', 'Animal_count', 'Animal_type', 'Scientific_name', 'Country', 'Animal_feed','Feed_cost']

class AnimalUpdate(UpdateView):
    model = Animal
    fields = ['id', 'Animal_species', 'Animal_count', 'Animal_type', 'Scientific_name', 'Country', 'Animal_feed','Feed_cost']

class AnimalDelete(DeleteView):
    model =Animal
    success_url = reverse_lazy('animal_details:index')

class MedicineDetail(generic.ListView):
    model = Medicine
    template_name = 'animal_details/med.html'

class MedicineCreate(CreateView):
    model = Medicine
    fields = ['Animal_id', 'Medicine_name', 'Medicine_cost']

class MedicineUpdate(UpdateView):
    model = Medicine
    fields = ['Animal_id', 'Medicine_name', 'Medicine_cost']

#-----------------------------------------------------------------------------------------------------------------------

class AccountCreate(CreateView):
    model=Accounts
    fields=['Income','Expenditure']

class AccountUpdate(UpdateView):
    model=Accounts
    fields=['Income','Expenditure']

class AccountDetail(generic.ListView):
    model=Accounts
    template_name='animal_details/acc.html'

    def get_queryset(self):
        return Accounts.objects.all()

class GrantsCreate(CreateView):
    model=Organisation_grants
    fields=['id','Organisation_name','Organisation_phno','Address','Amount']

class GrantsUpdate(UpdateView):
    model=Organisation_grants
    fields=['id','Organisation_name','Organisation_phno','Address','Amount']

class GrantsDetail(generic.ListView):
    model=Organisation_grants
    template_name='animal_details/grant.html'
#-----------------------------------------------------------------------------------------------------------------------
#staff
class StaffCreate(CreateView):
    model = Staff
    fields = ['id','Staff_name','Designation','Salary']
class StaffUpdate(UpdateView):
    model = Staff
    fields = ['id','Staff_name','Designation','Salary']

class StaffDetail(generic.ListView):
    model =Staff
    template_name='animal_details/staff.html'

    def get_queryset(self):
        return Staff.objects.all()

class StaffDelete(DeleteView):
    model=Staff
    success_url = reverse_lazy('animal_details:staff_detail')




#tourist
class TouristCreate(CreateView):
    model = Tourists
    fields = ['id','Tourists_name','Donation','GuideName','Phone_number']
class TouristUpdate(UpdateView):
    model = Tourists
    fields = ['id','Tourists_name','Donation','GuideName','Phone_number']
class TouristDelete(DeleteView):
    model = Tourists
    success_url = reverse_lazy('animal_details:index')
class TouristDetail(generic.ListView):
    model = Tourists
    template_name='animal_details/tourists.html'

animal_details/templates/animal_details/detail.html
{% extends 'animal_details/base.html' %}
{% block title %}Medicine  Details{% endblock %}
{% block body %}

<h1>{{animal.Animal_species}}</h1>
<h4>   id              = {{animal.id}}</h4>
<h4>   Count           = {{animal.Animal_count}}</h4>
<h4>   Scientific Name = {{animal.Scientific_name}}</h4>
<h4>   Type            = {{animal.Animal_type}}</h4>
<h4>   Country         = {{animal.Country}}</h4>
<h4>   Feed            = {{animal.Animal_feed}}</h4>
<h4>   Feed Cost       = {{animal.Feed_cost}}</h4>



{% endblock %}

animal_details/templates/animal_details/grant.html
{% extends 'animal_details/base.html' %}
{% block title %}Organisation_grant{% endblock %}
{% block body %}

<div class="container">
    <h2>Organisation_grants</h2>
    <table class="table table-hover">
        <thead>
          <tr>
             <th>Organisation_name</th>
              <th>Organisation_phno</th>
              <th>Address</th>
              <th>Amount</th>
              <th>Date</th>

          </tr>
        </thead>
        <tbody>
        {% for Organisation_grants in object.list %}
          <tr>
              <td>{{Organisation_grants.id}}</td>
              <td>{{Organisation_grants.Organisation_name}}</td>
              <td>{{Organisation_grants.phno}}</td>
              <td>{{Organisation_grants.Address}}</td>
              <td>{{Organisation_grants.Amount}}</td>
              <td>{{Organisation_grants.Date}}</td>
          </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

animal_details/templates/animal_details/grant_form.html
{% extends 'animal_details/base.html' %}
{% block title %}Add Grant Details{% endblock %}
{% block animal_active%}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'animal_details/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">submit</button>
                        </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

animal_details/templates/animal_details/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Prakruthi Sanctuary</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
 <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/0C922083-84F0-0B49-BA61-60D1C28E5BF0/main.js" charset="UTF-8"></script></head>
<body>

<nav class="orange accent-3" role="navigation">
    <div class="nav-wrapper container">
<a href="" class="brand-logo"><i class="material-icons">filter_vintage</i><h5 class="right"><font face="lucida calligraphy" font size="3">Prakruthi Sanctuary</font></h5></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'animal_details:login_user' %}"><i class="material-icons left">lock_outline</i><h5 class="right"><font face="verdana" font size="3">Login</font></h5></a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="{% url 'animal_details:login_user' %}"><i class="material-icons left">lock_outline</i>Login</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center white-text text-darken-4"><strong><font face="satisfy" ><i>Prakruthi Sanctuary</i></font></strong></h1>
        <div class="row center">
          <h5 class="header col s12 light light-blue-text text-lighten-4"><strong><i>Embracing The Nature!</i></strong></h5>
        </div>

        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="http://hddesktopwallpapers.in/wp-content/uploads/2015/09/wildlife-wallpapers-hd.jpg" alt="Unsplashed background img 1"></div>
  </div>
<div class="container">
<div class=" et_pb_row et_pb_row_0">


				<div class="et_pb_column et_pb_column_2_3  et_pb_column_0">

				<div class="et_pb_text et_pb_module et_pb_bg_layout_light et_pb_text_align_left  et_pb_text_0">

                  <blockquote><p><font face="lucida calligraphy" font size="4.7">Prakruthi Wildlife Sanctuary is a unique protected area located in the rain shadow region in the eastern slope of Western Ghats, in Karnataka. The area is diverse in eco systems and rich in ethnic cultural heritage. It is a well known repository of medicinal plants and supports a healthy population of grizzled giant squirrel, star tortoise, tufted grey langur, gaur, spotted deer, slender loris, wild elephant, crocodile, tiger, leopard and many a birds, insects and plants. There is an Interpretation Centre, two eco shops, an amenity centre, inspection bunglow, dormitory and cafeteria .</font></p></blockquote>

			</div> <!-- .et_pb_text -->
			</div> <!-- .et_pb_column -->
            </div>
</div>

<br><br>
<div class="container">

  <div class="slider">
      <ul class="slides">
      <li>
          <img src="https://lh3.googleusercontent.com/RlGJd-qe98zfA4ctqs-QTDG11GAJe1us7JHUkWEiIHznUV5GwMz9QJHPm27UX6WKHdw=h900" alt="">
          <div class="caption right-align">
            <h3><strong><font face="satisfy" ><i>Feel Their Freedom</i></font></strong></h3>

          </div>
      </li>

      <li>
          <img src="https://i.ytimg.com/vi/aYH_s2_6yso/maxresdefault.jpg" alt="">
          <div class="caption left-align">
          <h3><strong><font face="satisfy" ><i>See The New Colours</i></font></strong></h3>
          </div>
      </li>

      <li>
          <img src="http://ak4.picdn.net/shutterstock/videos/1919104/thumb/1.jpg" alt="">
          <div class="caption center-align">
          <h3><strong><font face="satisfy" ><i>Be A Part Of Them</i></font></strong></h3>
              </div>
      </li>

        <li>
          <img src="http://www.firsthdwallpapers.com/uploads/2013/04/Grass_wallpapers_512.jpg" alt="">
          <div class="caption center-align">
               <h3>Feel Their Love</h3>
          </div>
      </li>

        <li>
          <img src="http://hddesktopwallpapers.in/wp-content/uploads/2015/09/free-lion-pictures.jpg" alt="">
          <div class="caption right-align">
          <h3>Get Majestic</h3>
              </div>
      </li>

        <li>
          <img src="https://ak4.picdn.net/shutterstock/videos/13164224/thumb/1.jpg" alt="">
          <div class="caption center-align">
          <h3>Explore The New You</h3>
              </div>
      </li>
      </ul>

  </div>
  </div>
<div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">access_time</i></h2>
            <h5 class="center">Timing</h5>
<div class="container">
            <pre class="light">
  Monday     8AM-4PM
  Tuesday    8AM-4PM
  Wednesday  8AM-4PM
  Thursday   8AM-4PM
  Friday     8AM–4PM
  Saturday   8AM-4PM
  Sunday     8AM-5PM</pre>
  </div>
          </div>
        </div>



        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">pets</i></h2>
            <h5 class="center">Save Wildlife</h5>

            <p class="light">Wildlife is a precious gift of God to this planet. For maintaining a healthy ecological balance on this earth, animals, plants and marine species are as important as humans. But, sadly today, many of the animals and birds are getting endangered. If soon, no stringent steps are taken to save wildlife, it would not be long when they will find a place only on the list of extinct species. And that would not be all! The extinction of wildlife species will certainly have a fatal impact on human race as well. So, for us as humans, it becomes a great responsibility to save the wildlife, our planet and most importantly, our own selves.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Be A Part Of Us</h5>

            <p class="light">Wanna be a part of the coolest group.? Want to contribute in saving our nature and protecting animals? Join us as a VOLUNTEER and do your part. Be in a group of people who think like you and bring your best to save wildlife.Contact us for further details. </p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h4 class="header col s12 light white-text"><i>No kingdom without the King</i></h4>
          <br>
          <h1 class="white-text"><strong>SAVE TIGERS</strong></h1>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="http://gzsihai.com/data/out/153/im-500452411.jpg" alt="Unsplashed background img 2"></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>River Side, Watch Tower & Water Falls Trekking</h4>
          <img src="https://i2.wp.com/chinnar.org/wp-content/uploads/2015/01/koottar.jpg?w=1080" alt="">
          <p class="left-align light">The guided trekking to the dry deciduous forests and through the riparian forest along the river, visit to the archaeological remnants, the dolmens, and the sandal forests are all the more exciting. The luxurious waterfall, spreading over about 100 meters wide will steal the hearts of all. Bird and butterfly watching are added advantages. There are chances of wild life sighting on the way. Refreshments and complimentary snacks will be provided. Duration: 3 hours From 6am- 11am and 1 pm-4pm Tariff: Rs. 200/- (Indians) Rs. 300/- (Foreign National) (minimum Rs. 400/-)</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h2 class="header col s12 light white-text"><i>Save their innocent lives</i></h2>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="http://hd.wallpaperswide.com/thumbs/wild_animals-t2.jpg" alt="Unsplashed background img 3"></div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text"><strong><i>Contact Us</i></strong></h5>
          <pre class="grey-text text-lighten-4"><font face="verdana">
Forest Information Centre
Wildlife Warden’s Office, Chamarajanagar Dist.
Karnataka, India.
PIN:571 126
Tel: 91-4865-231587
Mob. 91 8301024187, 91 8547603199
E-mail: prakruthi@gmail.com</font></pre>


        </div>


  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script>
  $(document).ready(function(){

      $('.slider').slider();

      $('.parallax').parallax();
  });
  </script>


  </body>
</html>




animal_details/templates/animal_details/index.html
{% extends 'animal_details/base.html' %}

{% block body %}
<h3>Animals in Sanctary are:</h3>
    <ul>
        {% for animal in object_list %}
            <li><a href="{% url 'animal_details:detail' animal.id%}">{{animal.Animal_species}}</a>
            </li>
        {% endfor %}
    </ul>


{% endblock %}

animal_details/templates/animal_details/register.html
{% extends 'animal_details/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<center>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                   
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'animal_details/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'animal_details:login_user' %}">Click here</a> to log in.
                </div>
            
            </div>
        </div>
    </div>

</div>
</center>

{% endblock %}


animal_details/templates/animal_details/tourists.html

{% load staticfiles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'animal_details/style4.css' %}">

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>



    <div class="container"><a href="#" data-activates="nav-mobile" class="button-collapse top-nav waves-effect waves-light circle hide-on-large-only"><i class="material-icons">menu</i></a></div>
 <ul id="nav-mobile" class="side-nav fixed">
      <!--<ul id="nav-mobile" class="side-nav fixed">-->

     <li class="logo center yellow"><a id="logo-container" href="{% url 'animal_details:index' %}" class="brand-logo">
            <object id="front-page-logo" type="" ><i class="material-icons">filter_vintage</i></object></a>
         <h6 class="center"><strong>Prakruthi Sanctuary</strong></h6>
            <br>
     </li>

     <li class="bold"><a href="{% url 'animal_details:index' %}" class="waves-effect waves-red">Animals</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="#" class="waves-effect waves-teal">Employees</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="#" class="waves-effect waves-teal">Tourists</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="#" class="waves-effect waves-teal">Grants</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="#" class="waves-effect waves-teal">Medicine</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="#" class="waves-effect waves-teal">Accounts</a></li>
        <li><div class="divider"></div></li>
</ul></header>

<main>
    <nav>
        <div class="nav-wrapper center red">
            <a href="{% url 'animal_details:Tourist-detail' %}" class="brand-logo center">Tourists Details</a>

        </div>
    </nav>
  <br>
    <a href="{% url 'animal_details:Tourist-add' %}" class="btn btn-large waves-effect waves-light teal right z-depth-4"><i class="material-icons left">add</i>Add Tourist</a>
    <br>
    <br>
    <br>
    <br>



<div class="container">
    <table class="striped responsive-table">
        <thead>
          <tr>
              <th>Tourist id</th>
              <th>Tourists name</th>
              <th>Donation</th>
              <th>Date</th>
              <th>Guide name</th>
              <th>Phone number</th>
              <th>Update</th>
              <th>delete</th>
          </tr>
        </thead>
        <tbody>
        {% for Tourists in object_list %}
          <tr>
              <td>{{Tourists.id}}</td>
              <td>{{Tourists.Tourists_name}}</td>
              <td>{{Tourists.Donation}}</td>
              <td>{{Tourists.Date}}</td>
              <td>{{Tourists.GuideName}}</td>
              <td>{{Tourists.Phone_number}}</td>
              <td><a href="{% url 'animal_details:Tourist-update' Tourists.id %}" class="btn-floating waves-effect waves-light green "><i class="large material-icons">create</i></a></td>
              <td><a href="#" class="btn-floating red "><i class="large material-icons">delete</i></a></td>

          </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</main>

 <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script>  $(".button-collapse").sideNav({menuWidth:200,});</script>

